### ISSUE TITLE
Android SDK versions possible rebuild?

### ISSUE THREAD

**Issue by F1r3Hydr4nt** [sanukin39/UniLocalNotification#1]
Hey Dude,

Thanks a million for this super open source package!

I have a quick question; Are the minSDK & targetSDK values of 11 & 25 specifically chosen due to Android functionality or could I reduce them to fit my other dependencies?

Thanks again!

**Comment by F1r3Hydr4nt** [comment]
> unilocalnotification-release\AndroidManifest.xml:3] Main manifest has uses-sdk android:minSdkVersion='11' but library uses minSdkVersion='15'

Rebuild the unilocalnotification-release.aar?

**Comment by sanukin39** [comment]
Hi freddiehonohan,

This plugin works at sdk version 9. So you can set minSdkVersion=11 and rebuild aar!

Thanks!

**Comment by F1r3Hydr4nt** [comment]
Cool man, actually the issue was that I had some old Android compat .jar(s) and other libraries in the project which should have been removed as your package includes functioning ones which could replace them!
