### ISSUE TITLE
Android版ローカル通知について

### ISSUE THREAD

**Issue by ryh-tsuji** [sanukin39/UniLocalNotification#3]
はじめまして、突然のご連絡失礼致します！

Unityでローカル通知機能の実装を考えていた時に
sanukin39様のUniLocalNotificationを発見し使わせてもらっております。
大変便利で簡単に利用できてとても助かっています！
ありがとうございます！

そこで一点ご質問なのですが、
Android版でUniLocalNotificationを利用する際に
何か必要な設定などはありますでしょうか？
iOS版だと問題なく通知が出るのですが、Android版だと何故か表示がされていなくて・・・

現在Unity2018.2.0f2を利用しています。
AndroidStudio上のログで確認したところ
java.lang.ClassNotFoundException: Didn't find class" android.support.v4.app.NotificationManagerCompat"
というエラーが出ておりました。

初心者なので簡単なミスだったら大変恐縮なのですが、
ご教示頂ければと存じます。

何卒宜しくお願い致します。

**Comment by sanukin39** [comment]
ryh-tsuji さん、こんにちは

ライブラリの利用とエラーの報告ありがとうございます！
一部憶測となってしまい恐縮ですが、回答いたします。

問題はエラー文にある通りこのプラグインで利用しているクラスが参照できないことにあります。
そのクラスは以下のライブラリファイルに含まれており、これはUniLocalNotificationのリリースパッケージにも含まれています。
support-compat-25.3.1.aar

まずこのファイルが入っているかの確認と、このファイルをインスペクタービューで確認して、Androidプラットフォームのチェックが入っているかの確認をお願いします。

上記特に問題なかった場合は、お手数ですがこのプロジェクトにあるUnityのサンプルプロジェクトを単体でビルドしてAndroid端末での挙動を確認していただきたいです。

以上、よろしくお願いいたします。

**Comment by ryh-tsuji** [comment]
sanukin39 様

ご丁寧にご回答ありがとうございます！

確認したところ、パッケージのタイプが古かったようで、
support-compat-25.3.1.aarの入ったパッケージを入れたら
エラーはなくなりました。

しかし依然として通知は表示されない状況です。
端末内の通知設定を確認したところ、
![NotificationSettings](https://user-images.githubusercontent.com/46433088/63998666-946a9500-cb3c-11e9-81a0-fc5cf51e7769.png)
上記のように表示されていました。

ここが原因なのでしょうか。
能力不足でこれ以上の情報はわからないのですが
もしも何か解決策があればご教示頂ければと存じます。

度々で誠に恐縮ですが、
何卒宜しくお願い致します。

**Comment by sanukin39** [comment]
こちら確認してみました。

どうやらライブラリで利用しているメソッドが一部古くなっており、Android O以降で正常に通知が表示されていないようでした。
Android O以降では適切なメソッドで通知の作成を行うように対応したので、最新のリリースパッケージの利用をお願いします。

通知が正常に行われた場合、設定画面にもカテゴリが追加されます。

以上、よろしくお願いします。

**Comment by ryh-tsuji** [comment]
sanukin39 様

お世話になっております。
最新のパッケージ利用させて頂き、
無事に通知が表示されました！！
本当にありがとうございます！！！！！

お忙しい中ご対応頂き、本当に感謝しております。

これからも利用させて頂きますので、
今後とも何卒宜しくお願い致します！
